@startuml
actor Utilisateur as U
boundary IHM as I
participant System as S
participant Personne as P
participant Contact as Con
autonumber

U->I: Rechercher un Client

U->I: Rechercher un Client par ID
    I-[#red]>S: SM: RechercherClientID (idClient)
        loop for each idClient
        S-[#red]>C: SOM: getClientParID(idClient)
        C-[#0000FF]->S: idClient, Client
        end
    S-[#0000FF]->I: idClient,Client

U->I: Rechercher un Client par Denomination
    I-[#red]>S: SM: RechercherClientDenomination (Denomination)
        loop for each Denomination Client
        S-[#red]>C: SOM: getClientParDenomination(Denomination)
        C-[#0000FF]->S: idClient, Client
        end
    S-[#0000FF]->I: idClient,Client

U->I: Rechercher un Client par Nom Prenom
    I-[#red]>S: SM: RechercherClientNomPrenom (Nom, Prenom)
        loop for each Nom Prenom Client
        S-[#red]>C: SOM: getClientParNomPrenom(Nom, Prenom)
        C-[#0000FF]->S: idClient, Client
        end
    S-[#0000FF]->I: idClient,Client

U->I: Selection un Client

U->I: CU2:Consulter la Liste Personne de Client
U->I: CU3:Consulter la Liste de Contacts
U->I: CU2:Consulter la Liste des Contrats Souscrits


@enduml