@startuml
(*)  --> "Rechercher un Client"
"Rechercher un Client" --> "Rechercher un\n Client par ID"
"Rechercher un Client" --> "Rechercher un Client\n par dénomination"
"Rechercher un Client" --> "Rechercher un Client\n par nom"

"Rechercher un\n Client par ID" --> "Selectionner Client"
"Rechercher un Client\n par dénomination" --> "Selectionner Client"
"Rechercher un Client\n par nom" --> "Selectionner Client"

"Selectionner Client" --> "CU2: Consulter Liste\n Personne de Client"
"Selectionner Client" --> "CU3: Consulter liste contacts"
"Selectionner Client" --> "CU4: Consulter la liste des\n contrats souscrits"

@enduml