@startuml
(*) --> "Rechercher un\n Client par ID"
(*)  --> "Rechercher un Client\n par dénomination"
(*)  --> "Rechercher un Client\n par nom du Personne"

"Rechercher un\n Client par ID" --> "Selectionner Client"
"Rechercher un Client\n par dénomination" --> "Selectionner Client"
"Rechercher un Client\n par nom du Personne" --> "Selectionner Client"

"Selectionner Client" --> "CU2: Consulter liste\n Personne de Client"
"Selectionner Client" --> "CU3: Consulter Liste contacts"
"Selectionner Client" --> "CU4: Consulter liste des\n contrats souscrits"
"Selectionner Client" --> "Consulter liste des produits "
@enduml