@startuml
(*) --> "CU1 Identifier Client"
--> "Consulter Liste Personne de Client"

--> ===B1===
--> "Consulter une Personne"
--> "Modifier Donnees Personne"
--> ===B2===

--> ===B1===
--> "Retrirer une Personne de la liste"
--> ===B2===

--> ===B1===
--> "Modifier liste Personne de Client"
--> "Rechercher Personne dans liste de Client"
If "Personne Existe"
-->[Yes] "Ajouter une Personne existant dans la liste de Banque"
else
-->"Ajouter une Nouvelle Personne dans la liste de Client"
--> ===B2===

--> (*)
@enduml