@startuml

actor Utilisateur as U
boundary IHM as I
participant System as S
participant Client as C
participant Personne as P
participant Agent as A
participant Adress as Ad
'在personne和agent之间添加一个association 来储存最后一个modifier/ajouter 的agent的Id
autonumber

U->I: Identifier Client
    I-[#red]>S: SM:CU1

U->I: Consulter Liste Personne de Client
    I-[#red]>S: SM: obtenirListedePersonneClient (idClient)
        S-[#red]>C: SOM: getPersonnesParClient(idClient)
        C-[#0000FF]->S: list<idPersonne>
        loop for each idPersonne
        S-[#red]>P: SOM: getPersonnesParidPersonne(idPersonne)
        P-[#0000FF]->S: Personne
        end

    S-[#0000FF]->I: list<idPersonne, Personne>


U->I: Modifier Liste Personne de Client
U->I: Consulter Liste Personne de Client
alt
    U->I: Ajouter une Personne dans ce Liste Client

    U->I: Chercher Personne Par Nom/Prenom
        I-[#red]>S: SM: chercherPersonne(nom, prenom)
        S-[#0000FF]->I: list<idPersonne, Personne>
    alt  0 résulat cherché
    U->I: Créer une nouvelle personne
            I-[#red]>S: SM: créerNouvellePersonne(idPersonne, Personne, idClient)
            S-[#0000FF]->I: CRE
    else
    U->I: Choisir une Personne

    U->I: Ajouter Personne dans la Liste de Client
        I-[#red]>S: SM: ajouterPersonne(idPersonne, idClient)
        S-[#0000FF]->I: list<idPersonne, Personne>
    end
else
    U->I: Choisir une Personne
    U->I: Retirer Personne dans la Liste de Client
        I-[#red]>S: SM: retirerPersonne(idPersonne, idClient)
        S-[#0000FF]->I: list<idPersonne, Personne>
else
    U->I: Consulter Personne
        I-[#red]>S: SM: Consulter Personne(id Personne,id Client)
            S-[#red]>P: SOM: getPersonnesParidPersonne(idPersonne)
            P-[#0000FF]->S: <Personne,idAgent,idAdress,Adress>
            S-[#red]>A: SOM: getAgentParidAgent(idAgent)
            A-[#0000FF]->S: Agent
        S-[#0000FF]->I: <idPersonne, Personne, idAdress, Adress, Agent>
    U->I: Modifier Donnees Personne
        I-[#red]>S: SM: modifierPersonne(Adress, idPersonne, Personne, idAgent)
            S-[#red]>P: SOM: modifierPersonne(Adress, idPersonne, Personne, idAgent)
            P-[#0000FF]->S: CRE
        S-[#0000FF]->I: CRE
end



@enduml