@startuml
(*) --> "CU1 Sélectionner Client"
--> "Consulter Liste Personne de Client"

"Consulter Liste Personne de Client" --> "Consulter une Personne"
"Consulter Liste Personne de Client" --> "Retrirer une Personne\n de la liste"
"Consulter Liste Personne de Client" --> "Ajouter une\n personne au Client"

"Consulter une Personne"--> "Modifier Donnees Personne"


"Ajouter une\n personne au Client"--> "Rechercher Personne\n dans liste de Client"
If "Personne Existe"
-->[Yes] "Ajouter une\n Personne existant\n dans la liste de Banque"
else
-->[No] "Creation\n de la personne"
--> "Ajouter une\n Personne existant\n dans la liste de Banque"


@enduml