@startuml
(*) --> "CU1 Identifier Client"
--> "Consulter Liste Personne de Client"

--> ===B1===
--> "Consulter une Personne"
--> "Modifier Donnees Personne"
--> ===B2===

--> ===B1===
--> "Retrirer une Personne\n de la liste"
--> ===B2===

--> ===B1===
--> "Modifier liste\n Personne de Client"
--> "Rechercher Personne\n dans liste de Client"
If "Personne Existe"
-->[Yes] "Ajouter une\n Personne existant\n dans la liste de Banque"
else
-->"Ajouter une Nouvelle\n Personne dans\n la liste de Client"
--> ===B2===

--> (*)
@enduml