@startuml

actor Utilisateur as U
boundary IHM as I
participant System as S

autonumber

U->I: Identifier Client
    I-[#red]>S: SM:CU1

U->I: Consulter Liste Personne de Client
    I-[#red]>S: SM: obtenirListedePersonneClient (idClient)
    S-[#0000FF]->I: list<idPersonne, Personne>

U->I: Modifier Liste Personne de Client
U->I: Consulter Liste Personne de Client
alt
    U->I: Ajouter une Personne dans ce Liste Client

    U->I: Chercher Personne Par Nom/Prenom
        I-[#red]>S: SM: chercherPersonne(nom, prenom)
        S-[#0000FF]->I: list<idPersonne, Personne>
    alt  0 résulat cherché
    U->I: Créer une nouvelle personne
            I-[#red]>S: SM: créerNouvellePersonne(idPersonne, Personne, idClient)
            S-[#0000FF]->I: CRE
    else
    U->I: Choisir une Personne

    U->I: Ajouter Personne dans la Liste de Client
        I-[#red]>S: SM: ajouterPersonne(idPersonne, idClient)
        S-[#0000FF]->I: list<idPersonne, Personne>
    end
else
    U->I: Choisir une Personne
    U->I: Retirer Personne dans la Liste de Client
        I-[#red]>S: SM: retirerPersonne(idPersonne, idClient)
        S-[#0000FF]->I: list<idPersonne, Personne>
else
    U->I: Consulter Personnene
        I-[#red]>S: SM: Consulter Personne(id Personne,id Client)
        S-[#0000FF]->I: <idPersonne, Personne, id Adress, Adress>
    U->I: Modifier Donnees Personne
        I-[#red]>S: SM: modifierPersonne(idPersonne, id Client)
        S-[#0000FF]->I: CRE
end






@enduml