@startuml
actor Utilisateur as U
boundary IHM as I
participant Systeme as S
participant Contact as C
participant Contrat as CON
participant Offre as O

autonumber

U->I: Identifier Client
I-[#red]>S: SM:CU1
S-[#0000FF]->I: idClient,Client

U->I: Consulter liste contacts de client
I-[#red]>S: SM 3.1 consulterListeContacts(idClient)
S-[#red]>C: SOM 3.1 getContactClient(idClient)
C-[#0000FF]->S: List<idContact, Contact>
S-[#0000FF]->I: List<idContact, Contact>

alt
    U->I: Créer contact
    I-[#red]>S: SM 3.2 creerContact(idCLient,idAgent,Contact)
    S-[#red]>C: SOM 3.2 ajouterContact(idCLient,idAgent,Contact)
    C-[#0000FF]->S: CRE
    S-[#0000FF]->I: CRE
else
    U->I: Consulter onglet contact spontané/commercial
    U->I: Selectionner un contact
    U->I: Modifier un contact
    I-[#red]>S: SM 3.3 modifierContact(idContact,Contact)
    S-[#red]>C: SOM 3.3 modifierContact(idContact,Contact)
    C-[#0000FF]->S: CRE
    S-[#0000FF]->I: CRE
else
    U->I: Consulter onglet entretien
    U->I: Selectionner un entretien
    alt
        U->I: Consulter liste contrats de la banque
        I--[#red]>S: SM 3.4 consulterListeContrat()
        S-[#red]>CON: SOM 3.4 getListeContrat()
        CON-[#0000FF]->S: List<idContrat, Contrat, List<idDomaine, Domaine>>
        S-[#0000FF]->I: List<idContrat, Contrat, List<idDomaine, Domaine>>


        U->I: Consulter détail d'un contrat
        I-[#red]>S: SM 3.5 consulterDetailContrat(idContrat)
        S -[#red]> CON : SOM 3.5 getContratEtOption(idContrat)
        CON -[#0000FF]-> S : idContrat, Contrat, List<idOption, Option>
        S -[#0000FF]-> I: idContrat, Contrat, List<idOption, Option>

        U->I: Proposer un contrat
        I-[#red]>S: SM 3.6 proposerContrat(idContact,PropositionContrat,idContrat)
        S-[#red]>CON: SOM 3.6 formulerPropositionContrat(idContact,PropositionContrat,idContrat)
        CON-[#0000FF]->S: CRE
        S-[#0000FF]->I: CRE
    else
        U->I: Consulter liste offres de la banque
        I-[#red]>S: SM 3.7 consulterListeOffres()
        S-[#red]>O: SOM 3.7 getListeOffre()
        O-[#0000FF]->S: List<idOffre,Offre>
        S-[#0000FF]->I: List<idOffre,Offre>

        U->I: Consulter détaille d'une offre
        I-[#red]>S: SM 3.8 consulterDetailOffre(idOffre)
        S -[#red]> O : SOM 3.8 getDetailOffre(idOffre)
        O -[#0000FF]-> S : idOffre,Offre,list<idProduit,Produit>
        S-[#0000FF]->I: idOffre,Offre,list<idProduit,Produit>

        U->I: Proposer une offre
        I-[#red]>S: SM 3.9 proposerOffre(idContact,PropositionOffre,idOffre)
        S-[#red]>O: SOM 3.9 formulerPropositionOffre(idContact,PropositionOffre,idOffre)
        O-[#0000FF]->S: CRE
        S-[#0000FF]->I: CRE
    else
        U->I: Modifier entretien
        U->I: Enregistrer l'entretien
        I-[#red]>S: SM 3.3 modifierContact(idContact,Contact)
        S-[#red]>C: SOM 3.3 modifierContact(idContact,Contact)
        C-[#0000FF]->S: CRE
        S-[#0000FF]->I: CRE

    else
        U->I: Ajouter annotation
        U->I: Enregistrer annotation
        I-[#red]>S: SM 3.10 ajouterAnnotation(idContact,Annotation)
        S-[#red]>C: SOM 3.10: ajouterAnnotation(idContact, Annotation)
        C-[#0000FF]->S:CRE
        S-[#0000FF]->I: CRE

        U->I: Enregistrer l'entretien
        I-[#red]>S: SM 3.3 modifierContact(idContact,Contact)
        S-[#red]>C: SOM 3.3 modifierContact(idContact,Contact)
        C-[#0000FF]->S: CRE
        S-[#0000FF]->I: CRE
    end
end

@enduml