@startuml

(*) --> "CU1: Sélectionner client"
"CU1: Sélectionner client" --> "Consulter liste contacts de clients"
"Consulter liste contacts de clients" -->"Créer contact"


"Consulter liste contacts de clients" -->"Consulter onglet liste entretien"

"Consulter onglet liste entretien"-->"Selectionner entretien"

"Selectionner entretien"-->"Consulter liste offres de la banque"
-->"Consulter détaille d'une offre"
-->"Proposer une offre"

"Selectionner entretien"-->"Modifier entretien"
-->"Enregistrer l'entretien"

"Selectionner entretien"-->"Ajouter annotation"
-->"Enregistrer l'entretien"

"Selectionner entretien"-->"Consulter liste contrats de la banque"
-->"Consulter détaille d'un contrat"
-->"Proposer un contrat"

"Consulter liste contacts de clients" -->"Consulter onglet liste contact spontané/commercial"
-->"Selectionner un contact"
"Selectionner un contact"-->"Modifier contact"


@enduml